global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "scheduler"
    static_configs:
      - targets: ["localhost:2112"]

# Prometheus:
# Pulls metrics every 2 seconds
# From localhost:2112/metrics
# Metrics include:
# CPU usage per worker
# Memory usage per worker
# Task execution latency

# run on root (if prometheus is extracted here):
# prometheus --config.file=observability/prometheus.yml
# run this if prometheus is located elsewhere:
# ./prometheus --config.file="C:\Projects\Software\Adaptive task scheduler\adaptive-task-scheduler\observability\prometheus.yml"
# in windows: prometheus.exe --config.file="C:\Projects\Software\Adaptive task scheduler\adaptive-task-scheduler\observability\prometheus.yml"